- name: Install VScode
  hosts: localhost
  connection: local 
  #become: true
  become_user: root
  tasks:
    - name: Dependencies installation
      ansible.builtin.apt:
        update_cache: true
        name:
          - wget
          - gpg
          - apt-transport-https
        state: latest

    - name: update system and install code
      ansible.builtin.apt:
        update_cache: true
        name: code
        state: latest

- name: install java8, java11
  hosts: localhost
  connection: local 
  #become: true
  become_user: root
  tasks:
    - name: installation of openjdk-8
      ansible.builtin.apt:
        name: openjdk-8-jdk
        install_recommends: true

    - name: installation of openjdk-11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        install_recommends: true

- name: install python-is-python3
  hosts: localhost
  connection: local 
  #become: true
  become_user: root
  tasks:
    - name: installation of python-is-python3 package
      ansible.builtin.apt:
        name: python-is-python3
        state: latest

- name: terraform install
  hosts: localhost
  connection: local 
  #become: true
  become_user: root
  tasks: 
    - name: requirements install
      ansible.builtin.apt:
        name: 
          - software-common-properties
          - gpg

- name: install spotify
  hosts: localhost
  connection: local 
  #become: true
  become_user: root
  tasks:
    - name: add pubkey and add to apt-key
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com 
        id: f9a211976ed662f00e59361e5e3c45d7b312c643
        state: present

    - name: add repo to sources.list.d
      ansible.builtin.apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
    
    - name: install spotify client
      ansible.builtin.apt:
        name: spotify-client
        update_cache: yes

- name: Signal installation
  hosts: localhost
  connection: local 
  #become: true
  become_user: root
  tasks:
    - name: install Signal signing key
      ansible.builtin.shell: |
        wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
        
        cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
    
    - name: install client application
      ansible.builtin.apt: 
        name: signal-desktop
        update_cache: yes



- name: other installations
  hosts: localhost
  connection: local 
  become: yes
  become_user: root
  tasks: 
    - name: install discord 
      ansible.builtin.apt_key:
        deb: https://discord.com/api/download?platform=linux&format=deb

    - name: all installations
      ansible.builtin.apt:
        update_cache: yes
        name: 
          - htop
          - neofetch
          - keepassxc
          - qpdfview
          - nvtop
          - snapd
          - mangohud
          - k4dirstat
          - vlc
          - grsync
          - tree
          - lolcat
          - deluge
          - obs-studio

- name: snap and flatpack installations
  hosts: localhost
  connection: local 
  become: yes
  become_user: root
  tasks: 
    - name: flutter installation
      ansible.builtin.apt:
        name: 
          - curl
          - file
          - git
          - unzip
          - which
          - xz-utils
          - zip
          - libglu1-mesa
    
    - name: snap fluttes install
      ansible.builtin.shell: |
        sudo snap install flutter --classic

        flutter doctor -v

    - name: download and extract android studio
      ansible.builtin.unarchive:
        src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.2.1.15/android-studio-2021.2.1.15-linux.tar.gz
        dest: /home/nikkie/
        creates: /home/nikkie/android-studio
        remote_src: yes


- name: virtualization software
  hosts: localhost
  connection: local 
  become: yes
  become_user: root
  tasks:
    - name: kvm requirements install
      ansible.builtin.apt:
        name: 
          - bridge-utils
          - cpu-checker
          - libvirt-clients
          - libvirt-daemon
          - qemu 
          - qemu-kvm
    
    - name: virt-manager install
      ansible.builtin.apt: 
        name: virt-manager
        state: latest

- name: gaming stuff installation
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: lutris add ppa
      ansible.builtin.apt_repository: 
        repo: 'ppa: lutris-team/lutris'
    
    - name: lutris install
      ansible.builtin.apt: 
        name: lutris
        update_cache: yes

    - name: steam installation
      ansible.builtin.apt: 
        name: steam
    
    - name: wine add architecture
      ansible.builtin.shell: dpkg --add-architecture i386
      
    - name: wine dependencies install
      ansible.builtin.apt:
        name: 
          - libasound2-plugins:i386
          - libsdl2-2.0-0:i386
          - libdbus-1-3:i386
          - libsqlite3-0:i386
    
    - name: wine 32 and 64 install
      ansible.builtin.apt:
        name: 
          - wine64
          - wine32
    
    - name: gamemode install
      ansible.builtin.apt:
        name: gamemode

    - name: vulkan libraries install
      ansible.builtin.apt:
        name:
          - vulkan
          - vulkan-utils
          - libvulkan1
          - libvulkan1:i386