# to test in linux vm, install spice-vdagent into vm
# command to run: ansible-playbook -i localhost, -u root /home/linuxlite/Desktop/reinstall_ansible_apt.yaml

- name: Install VScode
  hosts: localhost
  connection: local
  become: true
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Dependencies installation
      ansible.builtin.apt:
        name:
          - wget
          - gpg
          - apt-transport-https
        update_cache: yes

    - name: Sleep for 5 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 5
      delegate_to: localhost

    - name: Add Microsoft key to keyring
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/keyrings/packages.microsoft.gpg

    - name: Add Microsoft VSCode to repo list
      #ansible.builtin.apt_repository:
      #  repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
      #  state: present
      ansible.builtin.shell: sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'

    - name: Update system and install code
      ansible.builtin.apt:
        update_cache: true
        name: code

    - name: Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

- name: Install java8, java11
  hosts: localhost
  connection: local
  become: true
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Installation of openjdk-8
      ansible.builtin.apt:
        name: openjdk-8-jdk
        install_recommends: true

    - name: Sleep for 10 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Installation of openjdk-11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        install_recommends: true

    - name: Sleep for 10 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 10
      delegate_to: localhost

- name: Install python-is-python3
  hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:
    - name: Installation of python-is-python3 package
      ansible.builtin.apt:
        name: python-is-python3
        state: latest

- name: Terraform install
  hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:
    - name: Dependencies download
      ansible.builtin.apt:
        name: gpg

    - name: Download terraform signing key and add to new keyring
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add terraform repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

      # E8A0 32E0 94D8 EB4E A189 D270 DA41 8C88 A321 9F7B
    - name: Update cache and install terraform
      ansible.builtin.apt:
        name: terraform
        update_cache: yes

    - name: Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

- name: Install spotify
  hosts: localhost
  connection: local
  become: true
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Add pubkey and add to apt-key
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: f9a211976ed662f00e59361e5e3c45d7b312c643
        state: present

    - name: Add repo to sources.list.d
      ansible.builtin.apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
  
    - name: Install spotify client
      ansible.builtin.apt:
        name: spotify-client
        update_cache: yes

    - name: Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

- name: Signal installation
  hosts: localhost
  connection: local
  become: true
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Add signal signing key
      ansible.builtin.apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
        keyring: /usr/share/keyrings/signal-desktop-keyring.gpg

    - name: Add signal repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
        state: present

    - name: Install signal client application
      ansible.builtin.apt:
        name: signal-desktop
        update_cache: yes

    - name: Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

- name: Other installations
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Install discord 
      ansible.builtin.apt:
        deb: https://discord.com/api/download?platform=linux&format=deb

    - name: All installations
      ansible.builtin.apt:
        update_cache: yes
        name:
          - htop
          - neofetch
          - keepassxc
          - qpdfview
          - nvtop
          - snapd
          - mangohud
          - k4dirstat
          - vlc
          - grsync
          - tree
          - lolcat
          - deluge
          - obs-studio

- name: snap and flatpack installations
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Flutter installation
      ansible.builtin.apt:
        name:
          - curl
          - file
          - git
          - unzip
          - xz-utils
          - zip
          - libglu1-mesa

    - name: Snap flutter install
      ansible.builtin.shell: |
        snap install flutter --classic

    - name: download and extract android studio
      ansible.builtin.unarchive:
        src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.2.1.15/android-studio-2021.2.1.15-linux.tar.gz
        dest: /home/nikkie/
        creates: /home/nikkie/android-studio
        remote_src: yes

- name: virtualization software
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: kvm requirements install
      ansible.builtin.apt:
        name:
          - bridge-utils
          - cpu-checker
          - libvirt-clients
          - libvirt-daemon
          - qemu
          - qemu-kvm

    - name: virt-manager install
      ansible.builtin.apt:
        name: virt-manager
        state: latest

- name: gaming stuff installation
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Lutris install
      ansible.builtin.apt:
        name: lutris
        update_cache: yes

    - name: Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

    - name: Steam installation
      ansible.builtin.apt:
        name: steam

    - name: Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

    - name: Wine add architecture
      ansible.builtin.shell: dpkg --add-architecture i386

    - name: Wine dependencies install
      ansible.builtin.apt:
        name:
          - libasound2-plugins:i386
          - libsdl2-2.0-0:i386
          - libdbus-1-3:i386
          - libsqlite3-0:i386

    - name: Wine 32 and 64 install
      ansible.builtin.apt:
        name:
          - wine64
          - wine32

    - name: Sleep for 10 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Gamemode install
      ansible.builtin.apt:
        name: gamemode

    - name: Vulkan libraries install
      ansible.builtin.apt:
        name:
          - libvulkan1
          - libvulkan1:i386

- name: Latex
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Install latexlive-extra
      ansible.builtin.apt:
        name: texlive-latex-extra

    - name: Install texlive specifics
      ansible.builtin.apt:
        name:
          - texlive-publishers
          - texlive-science

    - name: Install texlive japanese and german language package
      ansible.builtin.apt:
        name:
          - texlive-lang-german
          - texlive-lang-japanese

    - name: Latexmk for james-yu latex-workshop extension under VSCode
      ansible.builtin.apt:
        name: latexmk
